ascent.rabbitmq.exchange: ascent.main.exchange

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 0
spring:
    application:
        name: eventchannel
    rabbitmq:
        host: localhost
        password: guest
        port: 5672
        username: guest
